### PR TITLE
fix workerIds when maxThreads is undefined at passed options.

### PR DESCRIPTION
**Pull request by mshima**
Reproduction:

pool.mjs:
```
import Tinypool from 'tinypool';

const pool = new Tinypool({
  filename: new URL('./worker-id.mjs', import.meta.url).href,
});
pool.run();
pool.run();
pool.run();
pool.run();
pool.run();
```

worker-id.mjs
```
import { workerId } from 'tinypool';

export default function () {
  console.log('workerId', workerId);
}
```

`node pool.mjs`:
```
% node pool.mjs
workerId undefined
workerId undefined
workerId undefined
workerId 1
workerId undefined
```

### CODE REVIEW

**Comment by Aslemammad** [comment]
What issue this PR is trying to solve?

**Comment by mshima** [comment]
> What issue this PR is trying to solve?

The issue is the title, added a reproduction to the issue description.

**Comment by Aslemammad** [comment]
That's great, Thanks, could you please add a test case for it?

**Comment by Aslemammad** [comment]
Any updates on this @mshima?

**Comment by mshima** [comment]
@Aslemammad I don't think there should be a test for this.
I would change the options parse organization to something like:
```js
  const { maxThreads: userMaxThreads, minThreads, maxQueue, ...userOptions } = options;
  assert(userMaxThreads === undefined || minThreads === undefined || minThreads < userMaxThreads);
  const maxThreads = userMaxThreads ?? Math.max(kDefaultOptions.maxThreads, minThreads ?? 0);
  this.options = {
    ...kDefaultOptions,
    ...userOptions,
    filename,
    maxThreads,
    minThreads: minThreads ?? Math.min(kDefaultOptions.minThreads, maxThreads ?? Number.MAX_SAFE_INTEGER),
    maxQueue: maxQueue === 'auto' ? maxThreads ** 2 : maxQueue ?? kDefaultOptions.maxQueue,
  };
```

and don't always use `this.options` everywhere.

**Comment by Aslemammad** [comment]
Ok, so is there any change needed?

by test I mean, testing the `pool.mjs` behaviour, how was and how is it now.

**Comment by mshima** [comment]
> Ok, so is there any change needed?
> 
> by test I mean, testing the `pool.mjs` behaviour, how was and how is it now.

There is no behavior change, `workerIds` map was initialized without enough ids.

**Pull request merged**
